=== D4vidM4rtinez/learning-markupLanguages/XML/xsd/sociosLM.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="socios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="socio" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="DNI" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]{8}[A-Z]" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="fecha-nacimiento" type="xs:date"></xs:element>
                            <xs:element name="poblacion" type="xs:string"></xs:element>
                            <xs:element name="equipo" type="xs:string"></xs:element>
                            <xs:element name="ranking" type="xs:float"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== D4vidM4rtinez/learning-markupLanguages/XML/xsd/sociosLM.xml
<?xml version="1.0" encoding="UTF-8"?>
<socios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="sociosLM.xsd">
    <socio id="12">
        <nombre>Andreu Perez</nombre>
        <DNI>56565656X</DNI>
        <fecha-nacimiento>1990-03-07</fecha-nacimiento>
        <poblacion>Rubi</poblacion>
        <equipo>junior</equipo>
        <ranking>8.5</ranking>
    </socio>
    <socio id="7">
        <nombre>Aina Casas</nombre>
        <DNI>98989898L</DNI>
        <fecha-nacimiento>1998-06-15</fecha-nacimiento>
        <poblacion>Sabadell</poblacion>
        <equipo>pro</equipo>
        <ranking>9.7</ranking>
    </socio>
</socios>
